version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      all dependencies:
        pattern: "*"
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      all dependencies:
        pattern: "*"
