---
name: Run Tests

"on":
  push:
    branches:
      - master
  pull_request:

jobs:
  api_tests:
    name: Api Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run tests
        run: make test
  frontend_tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Run tests
        run: make test
  environment_tests:
    name: Devenv Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check user ids
        run: id
      - name: Build and run Dev Container tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: .devcontainer/test_dev_env.sh
